### ISSUE TITLE
Add full-text search example

### ISSUE THREAD

**Issue by simonschiller** [simonschiller/prefiller#1]
Room supports FTS3 and FTS4 virtual tables for [full-text search](https://developer.android.com/training/data-storage/room/defining-data#fts). We should add one such entity to the sample projects to showcase how they work in conjunction with Prefiller. Right now this is not possible, because the SQLite version bundled with Robolectric does not support the syntax of the statements generated by Room (see Robolectric issues [#3556](https://github.com/robolectric/robolectric/issues/3556) and [#4209](https://github.com/robolectric/robolectric/issues/4209)).

**Comment by guness** [comment]
I think we can close this. a solution has been merged already:

https://github.com/robolectric/robolectric/pull/5216
