### ISSUE TITLE
Add support for multiple script files

### ISSUE THREAD

**Issue by b4rd** [simonschiller/prefiller#36]
Hi!

First, thanks for this great plugin. :heart: 

My problem is that in my app I have multiple tables, and currently I have to merge their insert statements into one file, which is not pretty.
Could prefiller be extended with support for multiple script files?

**Comment by simonschiller** [comment]
Hi, thanks for the feedback and the suggestion. I think that makes a lot of sense to specify multiple script files (or even directories). I'll see if I can find a few minutes on the weekend or next week to implement this.

**Comment by simonschiller** [comment]
Should be available in the 1.4.0 release!

**Comment by b4rd** [comment]
Cool. Thanks. 😻
